export const NEW_PERSONAL_INFO = 'NEW_PERSONAL_INFO';
export const NEW_WORK_INFO = 'NEW_WORK_INFO';
export const NEW_EDUCATION_INFO = 'NEW_EDUCATION_INFO';
export const NEW_PROJECT_INFO = 'NEW_PROJECT_INFO';
export const NEW_MISC_INFO = 'NEW_MISC_INFO';
